import { DownloadButton } from '../pages/CV/CV.styles';

export interface PrintCVProps {
  /**
   * Filename in public/cv/, generated by `npm run build:cv-pdfs`. Required so each CV
   * variant offers its own PDF — previously every variant downloaded the same generic
   * file, so the Graphics and 3D pages handed visitors the full-stack CV.
   */
  file: string;
}

const PrintCV = ({ file }: PrintCVProps) => {
  const downloadPdf = () => {
    const link = document.createElement('a');
    link.href = `/cv/${file}`;
    link.download = file;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <DownloadButton
      onClick={downloadPdf}
      className="flex items-center gap-2 px-4 py-2 text-white bg-blue-600 rounded hover:bg-blue-700 transition-colors"
      aria-label="Export CV as PDF"
    >
      <span>Download PDF Version</span>
    </DownloadButton>
  );
};

export default PrintCV;
